# Site settings
title: MIST
email: michael.majurski@nist.gov
description: > # this means to ignore newlines until "baseurl:"
 A fast, accurate, and scalable Microscopy Image Stitching Tool.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: none
github_username:  mmajurski

# Build settings
markdown: kramdown
